import "./globals.css";
import { dana } from '@/utils/local_font'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" data-theme="light">
      <body className={`${dana.variable} font-sans`} >{children}</body>
    </html>
  );
}
